name: DailyPayments
main: indy.payments.main.Main
version: '${project.version}'
api-version: 1.18
authors: [ indyPlayGames ]

commands:
  payments:
    description: Daily Payments Setup.
    aliases: [payments]

permissions:
  payments.*:
    description: All permissions.
  payments.reload:
    description: Permission to reload plugin config.
  payments.toggle:
    description: Permission to toggle plugin.
  payments.config:
    description: Permission to change plugin config.
  payments.announce:
    description: Permission to being announced when someones pay or steal tax.
  payments.execute_punishments:
    description: Permission to execute punishments.
  payments.pay:
    description: Permission to pay tax.
  payments.steal:
    description: Permission to steal tax.
  payments.invincibility:
    description: Permission to being invincible to punishments.